// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckRuntimes() {
  return window['go']['main']['App']['CheckRuntimes']();
}

export function CreateUser(arg1) {
  return window['go']['main']['App']['CreateUser'](arg1);
}

export function ExecuteSQLExercise(arg1, arg2) {
  return window['go']['main']['App']['ExecuteSQLExercise'](arg1, arg2);
}

export function GetAchievements() {
  return window['go']['main']['App']['GetAchievements']();
}

export function GetArticle(arg1, arg2) {
  return window['go']['main']['App']['GetArticle'](arg1, arg2);
}

export function GetContentVersion() {
  return window['go']['main']['App']['GetContentVersion']();
}

export function GetGrammarExercise(arg1) {
  return window['go']['main']['App']['GetGrammarExercise'](arg1);
}

export function GetProgrammingExercise(arg1, arg2) {
  return window['go']['main']['App']['GetProgrammingExercise'](arg1, arg2);
}

export function GetSQLExercise(arg1) {
  return window['go']['main']['App']['GetSQLExercise'](arg1);
}

export function GetUserStats() {
  return window['go']['main']['App']['GetUserStats']();
}

export function ListGrammarExercises() {
  return window['go']['main']['App']['ListGrammarExercises']();
}

export function ListKnowledgeArticles(arg1) {
  return window['go']['main']['App']['ListKnowledgeArticles'](arg1);
}

export function ListKnowledgeCategories() {
  return window['go']['main']['App']['ListKnowledgeCategories']();
}

export function ListProgrammingExerciseMeta(arg1) {
  return window['go']['main']['App']['ListProgrammingExerciseMeta'](arg1);
}

export function ListProgrammingExercises(arg1) {
  return window['go']['main']['App']['ListProgrammingExercises'](arg1);
}

export function ListSQLExercises() {
  return window['go']['main']['App']['ListSQLExercises']();
}

export function ListUsers() {
  return window['go']['main']['App']['ListUsers']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function ResetProgress() {
  return window['go']['main']['App']['ResetProgress']();
}

export function RunFreeSQL(arg1, arg2) {
  return window['go']['main']['App']['RunFreeSQL'](arg1, arg2);
}

export function SearchContent(arg1) {
  return window['go']['main']['App']['SearchContent'](arg1);
}

export function SubmitCode(arg1) {
  return window['go']['main']['App']['SubmitCode'](arg1);
}

export function ValidateGrammar(arg1) {
  return window['go']['main']['App']['ValidateGrammar'](arg1);
}
