// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {user} from '../models';
import {sqllab} from '../models';
import {progress} from '../models';
import {knowledge} from '../models';
import {content} from '../models';
import {search} from '../models';
import {programming} from '../models';
import {grammarmodel} from '../models';

export function CheckRuntimes():Promise<Record<string, boolean>>;

export function CreateUser(arg1:user.CreateUserRequest):Promise<user.User>;

export function ExecuteSQLExercise(arg1:string,arg2:string):Promise<sqllab.EvaluationResult>;

export function GetAchievements():Promise<Array<progress.Achievement>>;

export function GetArticle(arg1:string,arg2:string):Promise<knowledge.Article>;

export function GetContentVersion():Promise<content.ContentVersion>;

export function GetGrammarExercise(arg1:string):Promise<content.Exercise>;

export function GetProgrammingExercise(arg1:string,arg2:string):Promise<content.Exercise>;

export function GetUserStats():Promise<progress.UserStats>;

export function ListGrammarExercises():Promise<Array<string>>;

export function ListKnowledgeArticles(arg1:string):Promise<Array<string>>;

export function ListKnowledgeCategories():Promise<Array<knowledge.Category>>;

export function ListProgrammingExercises(arg1:string):Promise<Array<string>>;

export function ListSQLExercises():Promise<Array<string>>;

export function ListUsers():Promise<Array<user.User>>;

export function Login(arg1:string,arg2:string):Promise<user.User>;

export function Logout():Promise<void>;

export function RunFreeSQL(arg1:string,arg2:string):Promise<sqllab.QueryResult>;

export function SearchContent(arg1:string):Promise<Array<search.SearchResult>>;

export function SubmitCode(arg1:programming.SubmitRequest):Promise<programming.SubmitResult>;

export function ValidateGrammar(arg1:string):Promise<grammarmodel.ValidationResult>;
